# Generated by Django 5.1.1 on 2024-10-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='subject',
        ),
    ]
